language: c++
install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install requests --user `whoami`
script:
  - ./build.sh
  - ./test.py
after_script:
  - cat bin/test_out.log
  - cat bin/test_err.log
