language: c++
install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install -r test/python_requirements.txt --user `whoami`
script:
  - ./build.sh
  - ./test.py
after_script:
  - cat gen/pre_output.cpp
  - cat bin/test_out.log
  - cat bin/test_err.log
notifications:
  email: false
